class EvaluatorAgent:
    """
    Evaluator Agent:
    - Validates each hypothesis generated by InsightAgent
    - Uses numeric evidence (CTR/ROAS changes)
    - Assigns final confidence scores
    - Labels each hypothesis as: Supported / Partially Supported / Not Supported
    """

    def __init__(self):
        pass

    def evaluate(self, campaign_name, df_summary, hypotheses):
        """
        df_summary contains:
        - ctr_change_pct
        - roas_change_pct

        hypotheses is a list from InsightAgent
        """

        final_results = []

        ctr_change = df_summary["ctr_change_pct"]
        roas_change = df_summary["roas_change_pct"]

        for hyp in hypotheses:
            text = hyp["hypothesis"]
            base_conf = hyp["confidence"]
            evidence = hyp["evidence"]

            result = {
                "campaign": campaign_name,
                "hypothesis": text,
                "initial_confidence": base_conf,
                "evidence": evidence,
                "validation": "",
                "final_confidence": 0.0
            }

            # --------------------------------------
            # RULE 1: Validate Creative Fatigue
            # --------------------------------------
            if "CTR" in text.upper() and "DROP" in evidence.upper():
                if ctr_change < -0.05:
                    result["validation"] = "Supported"
                    result["final_confidence"] = min(1.0, base_conf + 0.1)
                elif ctr_change < -0.02:
                    result["validation"] = "Partially Supported"
                    result["final_confidence"] = base_conf
                else:
                    result["validation"] = "Not Supported"
                    result["final_confidence"] = base_conf - 0.15

            # --------------------------------------
            # RULE 2: Validate ROAS-based hypotheses
            # --------------------------------------
            elif "ROAS" in evidence.upper() or "RETURN" in text.upper():
                if roas_change < -0.10:
                    result["validation"] = "Supported"
                    result["final_confidence"] = min(1.0, base_conf + 0.12)
                elif roas_change < -0.05:
                    result["validation"] = "Partially Supported"
                    result["final_confidence"] = base_conf
                else:
                    result["validation"] = "Not Supported"
                    result["final_confidence"] = base_conf - 0.10

            # --------------------------------------
            # RULE 3: General combined drop
            # --------------------------------------
            elif ctr_change < -0.03 and roas_change < -0.05:
                result["validation"] = "Supported"
                result["final_confidence"] = min(1.0, base_conf + 0.08)

            # --------------------------------------
            # RULE 4: Stable performance
            # --------------------------------------
            else:
                result["validation"] = "Not Supported"
                result["final_confidence"] = max(0.2, base_conf - 0.15)

            final_results.append(result)

        return final_results
